__author__ = 'Jonathan Rubin'

import os

def run(scriptdir, genomedir, bowtieindex, bowtieoptions, email):
    outfile = open(scriptdir + '/bam_to_5primebed.sbatch', 'w')
    outfile.write("#!/bin/bash\n")
    outfile.write("#SBATCH -p long\n")
    outfile.write("#SBATCH --nodes=1\n")
    outfile.write("#SBATCH --ntasks=1\n")
    outfile.write("#SBATCH --output /projects/dowellLab/groseq/pubgro/e_and_o/\n")
    outfile.write("#SBATCH --error /projects/dowellLab/groseq/pubgro/e_and_o/\n")
    outfile.write("#SBATCH --mail-type=ALL\n")
    outfile.write("#SBATCH --mail-user=" + email + "\n")
    outfile.write("#SBATCH --workdir=$SLURM_SUBMIT_DIR\n")
    outfile.write("echo Working directory is $SLURM_SUBMIT_DIR\n")
    outfile.write("module load bedtools/2.25.0\n")
    outfile.write("genome=" + genomedir + "\n")
    outfile.write("echo $infile\n")
    outfile.write("echo $genome\n")
    outfile.write("echo $outfile1\n")
    outfile.write("mkdir -p  $outdir/genomecoveragebed\n")
    outfile.write("mkdir -p $outdir/forFstitch\n")
    outfile.write("mkdir -p $outdir/genomecoveragebed/fortdf\n")
    outfile.write("/opt/bedtools/2.25.0/genomeCoverageBed -5 -bg -strand + -ibam $infile -g $genome > $outdir/forFstitch/$outfile1\n")
    outfile.write("/opt/bedtools/2.25.0/genomeCoverageBed -5 -bg -strand - -ibam $infile -g $genome > $outdir/forFstitch/$outfile2\n")
    outfile.write("/opt/bedtools/2.25.0/genomeCoverageBed -bg -strand + -ibam $infile -g $genome > $outdir/genomecoveragebed/$outfile3\n")
    outfile.write("/opt/bedtools/2.25.0/genomeCoverageBed -bg -strand - -ibam $infile -g $genome | awk -F '\t' -v OFS='\t' '{ $4 = - $4 ; print $0 }'> $outdir/genomecoveragebed/$outfile4\n")
    outfile.write("cat $outdir/genomecoveragebed/$outfile4 $outdir/genomecoveragebed/$outfile3 > $outdir/genomecoveragebed/fortdf/$outfile5.bed\n")
    outfile.write("/opt/bedtools/2.25.0/sortBed -i $outdir/genomecoveragebed/fortdf/$outfile5.bed >$outdir/genomecoveragebed/fortdf/$outfile5\n")
    outfile.close()
    
    outfile2 = open(scriptdir + '/bowtieafastq.sbatch','w')
    outfile2.write("#!/bin/bash\n")
    outfile2.write("#SBATCH -p long\n")
    outfile2.write("#SBATCH --nodes=1\n")
    outfile2.write("#SBATCH --ntasks=32\n")
    outfile2.write("#SBATCH --output /projects/dowellLab/groseq/pubgro/e_and_o/\n")
    outfile2.write("#SBATCH --error /projects/dowellLab/groseq/pubgro/e_and_o/\n")
    outfile2.write("#SBATCH --mail-type=ALL\n")
    outfile2.write("#SBATCH --mail-user=" + email + "\n")
    outfile2.write("#SBATCH --workdir=$SLURM_SUBMIT_DIR\n")
    outfile2.write("echo Working directory is $SLURM_SUBMIT_DIR\n")
    outfile2.write("module load bowtie/2.2.9\n")
    outfile2.write("echo $fastq1pathandfile\n")
    outfile2.write("echo ${outdir}${outfile}.sam\n")
    # outfile2.write("/opt/bowtie/bowtie2-2.0.2/bowtie2 -p32 " + bowtieoptions + " -un ${outdir}${outfile}.unmapped.fastq \\\n")
    outfile2.write("/opt/bowtie/2.2.9/bowtie2 -p32 " + bowtieoptions + " \\\n")
    outfile2.write(bowtieindex + " \\\n")
    outfile2.write("-U $fastq1pathandfile \\\n")
    outfile2.write("> ${outdir}${outfile}.sam \\\n")
    outfile2.write("2> ${outdir}${outfile}.stderr\n")
    outfile2.close()
